### ISSUE TITLE
Old style non-open-graph score tags are not handled

### ISSUE THREAD

**Issue by pushrbx** [pushrbx/python3-mal#28]
There is no span tag around the score here: https://myanimelist.net/manga/63
However there is a span tag around the score here: https://myanimelist.net/anime/32281/Kimi_no_Na_wa
```
Traceback (most recent call last):
  File "C:\Users\pushrbx\.pyenvs\scraping-test\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "C:\Users\pushrbx\Documents\Projects\it-scraper\mal_crawler\spiders.py", line 181, in parse
    parse_result = manga.parse(page)
  File "C:\Users\pushrbx\.pyenvs\scraping-test\lib\site-packages\myanimelist\media.py", line 337, in parse
    media_info = self.parse_sidebar(media_page)
  File "C:\Users\pushrbx\.pyenvs\scraping-test\lib\site-packages\myanimelist\manga.py", line 71, in parse_sidebar
    manga_info = super(Manga, self).parse_sidebar(manga_page)
  File "C:\Users\pushrbx\.pyenvs\scraping-test\lib\site-packages\myanimelist\media.py", line 256, in parse_sidebar
    score = float(utilities.css_select('span.dark_text + span', score_tag_results[0])[0].text)
IndexError: list index out of range
```

**Comment by pushrbx** [comment]
This should be the improvement of PR #26

**Comment by pushrbx** [comment]
Still has problems:
https://myanimelist.net/anime/8999/Origami_Warriors
```
Traceback (most recent call last):
  File "/home/pushrbx/python-envs/test-scraper/lib/python3.5/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/data/GitHub/it-scraper/mal_crawler/spiders.py", line 47, in parse
    parse_result = anime.parse(page)
  File "/home/pushrbx/python-envs/test-scraper/lib/python3.5/site-packages/myanimelist/media.py", line 363, in parse
    media_info = self.parse_sidebar(media_page)
  File "/home/pushrbx/python-envs/test-scraper/lib/python3.5/site-packages/myanimelist/anime.py", line 97, in parse_sidebar
    anime_info = super(Anime, self).parse_sidebar(anime_page)
  File "/home/pushrbx/python-envs/test-scraper/lib/python3.5/site-packages/myanimelist/media.py", line 263, in parse_sidebar
    score_tag.getparent().xpath(".//span[@itemprop='ratingCount']")[0].text.replace(',', ''))
IndexError: list index out of range
```
