### ISSUE TITLE
 Error with user endpoint

### ISSUE THREAD

**Issue by Stonedestroyer** [pushrbx/python3-mal#34]
>>> s.user('Xinil').load()
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\discord\python3-mal\myanimelist\user.py", line 646, in load
    self.set(self.parse(utilities.get_clean_dom(user_profile)))
  File "C:\discord\python3-mal\myanimelist\user.py", line 227, in parse
    user_info = self.parse_sidebar(user_page)
  File "C:\discord\python3-mal\myanimelist\user.py", line 210, in parse_sidebar
    user_info['id'] = int(all_comments_link.get('href').split('&id=')[1])
IndexError: list index out of range
>>>
```

**Comment by pushrbx** [comment]
Could you please include the page which caused the problem? It seems that there are cases where the link of the comments has less query params or something like that.

**Comment by pushrbx** [comment]
Nvm the above. It seems that they have removed the user id from the profile pages.

**Comment by pushrbx** [comment]
Fixed the issue, but in a way which requires a logged in session. Otherwise the user id stays -1.
