### ISSUE TITLE
Broken: image load is now driven by js on mal

### ISSUE THREAD

**Issue by pushrbx** [pushrbx/python3-mal#41]
```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/pushrbx/python3-mal/tests/anime_tests.py", line 149, in testAired
    assert self.spicy_wolf.aired == (
  File "/home/travis/build/pushrbx/python3-mal/myanimelist/base.py", line 87, in _decorator
    getattr(self, func_name)()
  File "/home/travis/build/pushrbx/python3-mal/myanimelist/media.py", line 603, in load
    self.set(self.parse(utilities.get_clean_dom(media_page)))
  File "/home/travis/build/pushrbx/python3-mal/myanimelist/media.py", line 375, in parse
    media_info = self.parse_sidebar(media_page)
  File "/home/travis/build/pushrbx/python3-mal/myanimelist/anime.py", line 101, in parse_sidebar
    anime_info = super(Anime, self).parse_sidebar(anime_page)
  File "/home/travis/build/pushrbx/python3-mal/myanimelist/media.py", line 174, in parse_sidebar
    media_info['picture'] = picture_tag.get('src').encode("utf-8").decode("utf-8")
AttributeError: 'NoneType' object has no attribute 'encode'
```

**Comment by pushrbx** [comment]
fixed
